---

# Languages

php:
    label: PHP
    logo: php
    message: 7.4
    link: https://www.php.net
    source: shields.io

symfony:
    label: Symfony
    logo: symfony
    message: 5.x
    link: https://symfony.com
    source: shields.io

ezplatform:
    label: eZ Platform
    logo: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB2aWV3Qm94PSIwIDAgMTY2LjcgMTY2LjciIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDE2Ni43IDE2Ni43IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxnPg0KCTxnPg0KCQk8Zz4NCgkJCTxnPg0KCQkJCTxyZWN0IHg9IjgiIHk9IjE1LjUiIHdpZHRoPSIxMjIuMyIgaGVpZ2h0PSIxMjIuMyIvPg0KCQkJCTxyZWN0IHg9IjE5LjkiIHk9IjI3LjQiIGZpbGw9IiNGRkZGRkYiIHdpZHRoPSI5OC42IiBoZWlnaHQ9Ijk4LjYiLz4NCgkJCQk8cmVjdCB4PSI1OC43IiB5PSI2NS44IiB3aWR0aD0iOTQuMSIgaGVpZ2h0PSI5NC4xIi8+DQoJCQkJPHJlY3QgeD0iNjkuOSIgeT0iNzciIGZpbGw9IiNGMTVBMjIiIHdpZHRoPSI3MS41IiBoZWlnaHQ9IjcxLjUiLz4NCgkJCTwvZz4NCgkJPC9nPg0KCTwvZz4NCjwvZz4NCjwvc3ZnPg0K
    message: 3.x
    link: https://ezplatform.com
    source: shields.io

reactjs:
    label: React JS
    logo: react
    link: https://reactjs.org
    source: shields.io

javascript:
    label: Javascript
    logo: javascript
    message: ES6
    link: https://www.w3schools.com/js/js_es6.asp
    source: shields.io

typecript:
    label: TypeScript
    logo: typescript
    link: https://www.typescriptlang.org
    source: shields.io

html:
    label: HTML
    logo: html5
    link: https://www.w3.org/html
    source: shields.io

css:
    label: CSS
    logo: css3
    link: https://www.w3.org/Style/CSS/specs.en.html
    source: shields.io

bootstrap:
    label: Bootstrap
    logo: bootstrap
    link: https://getbootstrap.com
    source: shields.io

# Services

mysql:
    label: MySQL
    logo: mysql
    message: 8.x
    link: https://www.mysql.com
    source: shields.io

mongodb:
    label: MongoDB
    logo: mongodb
    message: 4.x
    link: https://www.mongodb.com/
    source: shields.io

redis:
    label: Redis
    logo: redis
    link: https://redislabs.com
    source: shields.io

elasticsearch:
    label: ElasticSearch
    logo: elasticsearch
    link: https://www.elastic.co
    source: shields.io

solr:
    label: Solr
    logo: apache-solr
    link: https://lucene.apache.org/solr
    source: shields.io

varnish:
    label: Varnish
    logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAAXNSR0IArs4c6QAAAIRlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAA6gAwAEAAAAAQAAAA4AAAAATspU+QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAAAgJJREFUKBV1UjFrFEEUfu/tZkl2T6LeXsR0gtichZJCRBCES6dYmRMtBAXBUt2kshiwsAj+ABHSKKjJL1ivOAXBQiXVKVrZKHibQ5LLmtxmd8Y377JGDn0wb2bezPfNN+89hP+ZMQiIxh6H8/F5BDqOGla7D2djG0Pr/mE2LqDafOs5TUw2jc6ZxwG9vbGULM7eIAEpRWBfKE21HbsMF+KrFBxs6l/rOzBIMwYV5E9er0atiwTK8FBaZFkCa9/3CQkaPG3yARg0TIseBwtT5EBkTrmgUB+K4uBH5e2WEPA1mH4lMgHoE46NAw42c8Za7ZpcD0xGnym8G89odL6G6ZkY1LLH3zbQSQQ4FRx+rDd776hS88HzPaqE4zr9+Trx3zwhdJwT7tSREMltVNcnaiLVOpbdUfUsCNyzJl1b0Fn6tOiv3U4CtzFUdmnZCaOXd8IoviAgeZVXHAfVdiU26ph0L5Ojh+XeEtRrOEzYB4BHN21dbAkM1tXHsQ50NahzOdftHmfhGn911XPp1rcHjZ6UarcZSj6WgqYDbQGFUesKVar3zdYGYHDgaNbv2iQ1YW7FlqkoQXberdsXkUyEM8B1MsVOj7Npe+ekXF6ZY9BfDfIHOH1M0q9BP9PbfSB/f5WHxSwJUJI07FvZs9tLjnQQaltXbo3L3OHvk8XGi/Li6Pwb353L6BLKBBsAAAAASUVORK5CYII=
    link: https://varnish-cache.org
    source: shields.io

# Hosting

platformsh:
    label: Platform.sh
    logo: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MCA1MCI+PGRlZnM+PHN0eWxlPi5iY2FjNjk1YS1hMGE0LTQxMDAtODRmZC02MWVjYzQyMTA5MWN7ZmlsbDojMGEwYTBhO30uZmM4ZGQ0MjItZmIwMi00ODIyLWE1N2UtYzIwYzhiNWVlZjdje2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlBsYXRmb3Jtc2hfaWNvbl93aGl0ZTwvdGl0bGU+PGcgaWQ9ImI1ZjliYjQ5LTE2MTQtNGIyMi04YzA0LWY1MTgyYzE4MDNmNSIgZGF0YS1uYW1lPSJMYXllciAyIj48ZyBpZD0iYjJhMjg1NjAtNWU0OC00NDM1LWFjY2QtZTE0OWI0Zjk2Y2MwIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxyZWN0IGNsYXNzPSJiY2FjNjk1YS1hMGE0LTQxMDAtODRmZC02MWVjYzQyMTA5MWMiIHdpZHRoPSI1MCIgaGVpZ2h0PSI1MCIvPjxyZWN0IGNsYXNzPSJmYzhkZDQyMi1mYjAyLTQ4MjItYTU3ZS1jMjBjOGI1ZWVmN2MiIHg9IjEwLjczIiB5PSIxMC43MiIgd2lkdGg9IjI4LjU1IiBoZWlnaHQ9IjExLjM1Ii8+PHJlY3QgY2xhc3M9ImZjOGRkNDIyLWZiMDItNDgyMi1hNTdlLWMyMGM4YjVlZWY3YyIgeD0iMTAuNzMiIHk9IjM1LjQyIiB3aWR0aD0iMjguNTUiIGhlaWdodD0iMy44NiIvPjxyZWN0IGNsYXNzPSJmYzhkZDQyMi1mYjAyLTQ4MjItYTU3ZS1jMjBjOGI1ZWVmN2MiIHg9IjEwLjczIiB5PSIyNS43NCIgd2lkdGg9IjI4LjU1IiBoZWlnaHQ9IjUuODIiLz48L2c+PC9nPjwvc3ZnPg==
    link: https://platorm.sh
    source: shields.io

aws:
    label: AWS
    logo: amazon-aws
    link: https://aws.amazon.com
    source: shields.io

docker:
    label: Docker
    logo: docker
    link: https://docker.com
    source: shields.io

# Tools

git:
    label: Git
    logo: git
    link: https://git-scm.com
    source: shields.io

github:
    label: Github
    logo: github
    link: https://github.com
    source: shields.io

bitbucket:
    label: Bitbucket
    logo: bitbucket
    link: https://bitbucket.com
    source: shields.io

gitlab:
    label: Gitlab
    logo: gitlab
    link: https://gitlab.com
    source: shields.io

travis:
    label: Travis
    logo: travis
    link: https://travis-ci.com
    source: shields.io

githubactions:
    label: Github Actions
    logo: github-actions
    link: https://github.com/features/actions
    source: shields.io

# Social

twitter:
    label: Plopix
    logo: twitter
    link: https://twitter.com/plopix
    source: shields.io

linkedin:
    label: Sebastien Morel
    logo: linkedin
    link: https://linkedin.com/in/sebastienmorel
    source: shields.io
